
export const ADDITEM="ADDITEM";
export const REMOVEITEM="REMOVEITEM";

export const INITFETCH="INITFETCH";
export const FETCHINGRE_SUCCESS="FETCHINGRE_SUCCESS";
export const FETCHINGRE_FAILED="FETCHINGRE_FAILED";
export const RESETINGRE="RESETINGRE";
export const CANCELMODAL="CANCELMODAL";

export const RESETPURCHASE="RESETPURCHASE";
export const INITPOSTORDER="INITPOSTORDER";
export const POSTORDER_SUCCESS="POSTORDER_SUCCESS";
export const POSTORDER_FAILED="POSTORDER_FAILED";
export const POST_CANCEL="POST_CANCEL";

export const INITGETORDER="INITGETORDER";
export const GETORDER_SUCCESS="GETORDER_SUCCESS";
export const GETORDER_FAILED="GETORDER_FAILED";

export const INITAUTH="INITAUTH";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILED="AUTH_FAILED";
export const AUTH_LOGOUT="AUTH_LOGOUT";


export const LOGOUT="LOGOUT";